version: '3'
services:
  webserver:
    #depends_on: getdata
    #build: ./web/
    image: flipr-webserver:latest
    ports:
      - "8080:80"
    volumes:
      - web:/usr/share/nginx/html/
      - code:/usr/local/src/
    restart: always
  getdata:
    #build: ./python/
    image: flipr-getdata:latest
    volumes:
      - code:/usr/local/src/
volumes:
  web: {}
  code: {}